substitutions:
  id_prefix: aq_mini
  node_name: mista-aq-mini
external_components:
  - source:
      type: git
      url: https://github.com/tuct/esphome_external_components
      ref: main  
sensor:
  - platform: sen6x
    id: sen54
    pm_1_0:
      name: "PM <1µm Weight concentration ${node_name}"
      id: ${id_prefix}_pm10
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 9
            send_every: 1
    pm_2_5:
      name: "PM <2.5µm Weight concentration ${node_name}"
      id: ${id_prefix}_pm25
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 9
            send_every: 1
    pm_4_0:
      name: "PM <4µm Weight concentration ${node_name}"
      id: ${id_prefix}_pm40
      accuracy_decimals: 1
    pm_10_0:
      name: "PM <10µm Weight concentration ${node_name}"
      id: ${id_prefix}_pm100
      accuracy_decimals: 1
    nox:
      name: "NOX ${node_name}"
      id: ${id_prefix}_nox
      accuracy_decimals: 1
    co2:
      name: "CO2 ${node_name}"
      id: ${id_prefix}_co2
      accuracy_decimals: 1
    temperature:
      name: "Temperature top ${node_name}"
      accuracy_decimals: 1
      id: ${id_prefix}_temperature_top
    humidity:
      name: "Humidity ${node_name}"
      accuracy_decimals: 0
      id: ${id_prefix}_humidity
    voc:
      name: "VOC ${node_name}"
      id: ${id_prefix}_voc
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
      filters:
        - sliding_window_moving_average:
            window_size: 9
            send_every: 1
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    store_baseline: true
    update_interval: 10s